{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sarajaved797/job-offer-comparison-app/blob/main/job_offer_comparison_app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit\n",
        "\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "\n",
        "# ---------- Define weight sliders ----------\n",
        "st.title(\"🎯 Job Offer Comparison App\")\n",
        "st.markdown(\"Adjust what's important to you:\")\n",
        "\n",
        "salary_weight = st.slider(\"💰 Salary\", 0.0, 1.0, 0.25)\n",
        "bonus_weight = st.slider(\"🎁 Bonus\", 0.0, 1.0, 0.1)\n",
        "remote_weight = st.slider(\"🏠 Remote Work\", 0.0, 1.0, 0.1)\n",
        "match_weight = st.slider(\"💼 401k Match\", 0.0, 1.0, 0.05)\n",
        "vesting_weight = st.slider(\"⏳ Vesting Speed\", 0.0, 1.0, 0.05)\n",
        "edu_weight = st.slider(\"🎓 Education Help\", 0.0, 1.0, 0.05)\n",
        "promotion_weight = st.slider(\"🚀 Promotion Path\", 0.0, 1.0, 0.1)\n",
        "relocation_weight = st.slider(\"📦 Relocation Help\", 0.0, 1.0, 0.05)\n",
        "culture_weight = st.slider(\"🌱 Culture\", 0.0, 1.0, 0.1)\n",
        "micro_weight = st.slider(\"🧠 Autonomy\", 0.0, 1.0, 0.05)\n",
        "brand_weight = st.slider(\"🏢 Industry Reputation\", 0.0, 1.0, 0.05)\n",
        "gap_weight = st.slider(\"🔄 Employment Gap Leniency\", 0.0, 1.0, 0.025)\n",
        "deadline_weight = st.slider(\"⏰ Decision Deadline\", 0.0, 1.0, 0.025)\n",
        "\n",
        "weights = {\n",
        "    'salary': salary_weight,\n",
        "    'bonus': bonus_weight,\n",
        "    'remote_score': remote_weight,\n",
        "    '401k_match_percent': match_weight,\n",
        "    'vesting_score': vesting_weight,\n",
        "    'edu_score': edu_weight,\n",
        "    'promotion_score': promotion_weight,\n",
        "    'relocation_score': relocation_weight,\n",
        "    'culture_rating': culture_weight,\n",
        "    'micro_score': micro_weight,\n",
        "    'brand_score': brand_weight,\n",
        "    'gap_score': gap_weight,\n",
        "    'deadline_score': deadline_weight\n",
        "}\n",
        "\n",
        "# ---------- Background Color Map ----------\n",
        "priority_color_map = {\n",
        "    'salary': '#e6ffe6',\n",
        "    'bonus': '#e6ffe6',\n",
        "    'remote_score': '#e6f0ff',\n",
        "    'promotion_score': '#fff5e6',\n",
        "    'culture_rating': '#f2e6ff',\n",
        "    'micro_score': '#fff9e6',\n",
        "}\n",
        "\n",
        "top_factor = max(weights, key=weights.get)\n",
        "bg_color = priority_color_map.get(top_factor, '#ffffff')\n",
        "\n",
        "st.markdown(\n",
        "    f\"\"\"\n",
        "    <style>\n",
        "        .stApp {{\n",
        "            background-color: {bg_color};\n",
        "        }}\n",
        "    </style>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "# ---------- Sample Offers ----------\n",
        "data = [\n",
        "    {\n",
        "        'offer_id': 'Offer A',\n",
        "        'salary': 55000,\n",
        "        'bonus': 5000,\n",
        "        'remote_type': 'On-site',\n",
        "        '401k_match_percent': 5,\n",
        "        'vesting_schedule_years': 4,\n",
        "        'education_assistance': 'Yes',\n",
        "        'promotion_path': 'Clear',\n",
        "        'relocation_help': 'Yes',\n",
        "        'culture_rating': 8,\n",
        "        'micromanagement_level': 'Low',\n",
        "        'industry_brand_strength': 'Strong',\n",
        "        'employment_gap_months': 6,\n",
        "        'candidate_background': 'Career Switch',\n",
        "        'decision_deadline_days': 7\n",
        "    },\n",
        "    {\n",
        "        'offer_id': 'Offer B',\n",
        "        'salary': 58000,\n",
        "        'bonus': 4000,\n",
        "        'remote_type': 'Remote',\n",
        "        '401k_match_percent': 3,\n",
        "        'vesting_schedule_years': 2,\n",
        "        'education_assistance': 'No',\n",
        "        'promotion_path': 'Ambiguous',\n",
        "        'relocation_help': 'No',\n",
        "        'culture_rating': 7,\n",
        "        'micromanagement_level': 'Medium',\n",
        "        'industry_brand_strength': 'Medium',\n",
        "        'employment_gap_months': 0,\n",
        "        'candidate_background': 'Experienced',\n",
        "        'decision_deadline_days': 14\n",
        "    }\n",
        "]\n",
        "\n",
        "df = pd.DataFrame(data)\n",
        "\n",
        "# ---------- Map to Scores ----------\n",
        "remote_map = {'Remote': 3, 'Hybrid': 2, 'On-site': 1}\n",
        "promo_map = {'Clear': 3, 'Ambiguous': 2, 'None': 1}\n",
        "micro_map = {'Low': 3, 'Medium': 2, 'High': 1}\n",
        "brand_map = {'Strong': 3, 'Medium': 2, 'Weak': 1}\n",
        "binary_map = {'Yes': 1, 'No': 0}\n",
        "\n",
        "df['remote_score'] = df['remote_type'].map(remote_map)\n",
        "df['promotion_score'] = df['promotion_path'].map(promo_map)\n",
        "df['micro_score'] = df['micromanagement_level'].map(micro_map)\n",
        "df['brand_score'] = df['industry_brand_strength'].map(brand_map)\n",
        "df['edu_score'] = df['education_assistance'].map(binary_map)\n",
        "df['relocation_score'] = df['relocation_help'].map(binary_map)\n",
        "\n",
        "df['vesting_score'] = 1 / df['vesting_schedule_years']\n",
        "df['gap_score'] = 1 / (df['employment_gap_months'] + 1)\n",
        "df['deadline_score'] = 1 / (df['decision_deadline_days'] + 1)\n",
        "\n",
        "# ---------- Score Calculation ----------\n",
        "def weighted_score(row):\n",
        "    return sum(row[factor] * weight for factor, weight in weights.items())\n",
        "\n",
        "df['total_score'] = df.apply(weighted_score, axis=1)\n",
        "\n",
        "# ---------- Output ----------\n",
        "st.header(\"📊 Offer Scores\")\n",
        "st.dataframe(df[['offer_id', 'total_score']])\n",
        "\n",
        "best_offer = df.loc[df['total_score'].idxmax()]['offer_id']\n",
        "st.success(f\"✅ Based on your preferences, **{best_offer}** is the better offer.\")\n",
        "\n",
        "!pip install streamlit\n",
        "\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "\n",
        "# ---------- Define weight sliders ----------\n",
        "st.title(\"🎯 Job Offer Comparison App\")\n",
        "st.markdown(\"Adjust what's important to you:\")\n",
        "\n",
        "salary_weight = st.slider(\"💰 Salary\", 0.0, 1.0, 0.25)\n",
        "bonus_weight = st.slider(\"🎁 Bonus\", 0.0, 1.0, 0.1)\n",
        "remote_weight = st.slider(\"🏠 Remote Work\", 0.0, 1.0, 0.1)\n",
        "match_weight = st.slider(\"💼 401k Match\", 0.0, 1.0, 0.05)\n",
        "vesting_weight = st.slider(\"⏳ Vesting Speed\", 0.0, 1.0, 0.05)\n",
        "edu_weight = st.slider(\"🎓 Education Help\", 0.0, 1.0, 0.05)\n",
        "promotion_weight = st.slider(\"🚀 Promotion Path\", 0.0, 1.0, 0.1)\n",
        "relocation_weight = st.slider(\"📦 Relocation Help\", 0.0, 1.0, 0.05)\n",
        "culture_weight = st.slider(\"🌱 Culture\", 0.0, 1.0, 0.1)\n",
        "micro_weight = st.slider(\"🧠 Autonomy\", 0.0, 1.0, 0.05)\n",
        "brand_weight = st.slider(\"🏢 Industry Reputation\", 0.0, 1.0, 0.05)\n",
        "gap_weight = st.slider(\"🔄 Employment Gap Leniency\", 0.0, 1.0, 0.025)\n",
        "deadline_weight = st.slider(\"⏰ Decision Deadline\", 0.0, 1.0, 0.025)\n",
        "\n",
        "weights = {\n",
        "    'salary': salary_weight,\n",
        "    'bonus': bonus_weight,\n",
        "    'remote_score': remote_weight,\n",
        "    '401k_match_percent': match_weight,\n",
        "    'vesting_score': vesting_weight,\n",
        "    'edu_score': edu_weight,\n",
        "    'promotion_score': promotion_weight,\n",
        "    'relocation_score': relocation_weight,\n",
        "    'culture_rating': culture_weight,\n",
        "    'micro_score': micro_weight,\n",
        "    'brand_score': brand_weight,\n",
        "    'gap_score': gap_weight,\n",
        "    'deadline_score': deadline_weight\n",
        "}\n",
        "\n",
        "# ---------- Background Color Map ----------\n",
        "priority_color_map = {\n",
        "    'salary': '#e6ffe6',\n",
        "    'bonus': '#e6ffe6',\n",
        "    'remote_score': '#e6f0ff',\n",
        "    'promotion_score': '#fff5e6',\n",
        "    'culture_rating': '#f2e6ff',\n",
        "    'micro_score': '#fff9e6',\n",
        "}\n",
        "\n",
        "top_factor = max(weights, key=weights.get)\n",
        "bg_color = priority_color_map.get(top_factor, '#ffffff')\n",
        "\n",
        "st.markdown(\n",
        "    f\"\"\"\n",
        "    <style>\n",
        "        .stApp {{\n",
        "            background-color: {bg_color};\n",
        "        }}\n",
        "    </style>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "# ---------- Sample Offers ----------\n",
        "data = [\n",
        "    {\n",
        "        'offer_id': 'Offer A',\n",
        "        'salary': 55000,\n",
        "        'bonus': 5000,\n",
        "        'remote_type': 'On-site',\n",
        "        '401k_match_percent': 5,\n",
        "        'vesting_schedule_years': 4,\n",
        "        'education_assistance': 'Yes',\n",
        "        'promotion_path': 'Clear',\n",
        "        'relocation_help': 'Yes',\n",
        "        'culture_rating': 8,\n",
        "        'micromanagement_level': 'Low',\n",
        "        'industry_brand_strength': 'Strong',\n",
        "        'employment_gap_months': 6,\n",
        "        'candidate_background': 'Career Switch',\n",
        "        'decision_deadline_days': 7\n",
        "    },\n",
        "    {\n",
        "        'offer_id': 'Offer B',\n",
        "        'salary': 58000,\n",
        "        'bonus': 4000,\n",
        "        'remote_type': 'Remote',\n",
        "        '401k_match_percent': 3,\n",
        "        'vesting_schedule_years': 2,\n",
        "        'education_assistance': 'No',\n",
        "        'promotion_path': 'Ambiguous',\n",
        "        'relocation_help': 'No',\n",
        "        'culture_rating': 7,\n",
        "        'micromanagement_level': 'Medium',\n",
        "        'industry_brand_strength': 'Medium',\n",
        "        'employment_gap_months': 0,\n",
        "        'candidate_background': 'Experienced',\n",
        "        'decision_deadline_days': 14\n",
        "    }\n",
        "]\n",
        "\n",
        "df = pd.DataFrame(data)\n",
        "\n",
        "# ---------- Map to Scores ----------\n",
        "remote_map = {'Remote': 3, 'Hybrid': 2, 'On-site': 1}\n",
        "promo_map = {'Clear': 3, 'Ambiguous': 2, 'None': 1}\n",
        "micro_map = {'Low': 3, 'Medium': 2, 'High': 1}\n",
        "brand_map = {'Strong': 3, 'Medium': 2, 'Weak': 1}\n",
        "binary_map = {'Yes': 1, 'No': 0}\n",
        "\n",
        "df['remote_score'] = df['remote_type'].map(remote_map)\n",
        "df['promotion_score'] = df['promotion_path'].map(promo_map)\n",
        "df['micro_score'] = df['micromanagement_level'].map(micro_map)\n",
        "df['brand_score'] = df['industry_brand_strength'].map(brand_map)\n",
        "df['edu_score'] = df['education_assistance'].map(binary_map)\n",
        "df['relocation_score'] = df['relocation_help'].map(binary_map)\n",
        "\n",
        "df['vesting_score'] = 1 / df['vesting_schedule_years']\n",
        "df['gap_score'] = 1 / (df['employment_gap_months'] + 1)\n",
        "df['deadline_score'] = 1 / (df['decision_deadline_days'] + 1)\n",
        "\n",
        "# ---------- Score Calculation ----------\n",
        "def weighted_score(row):\n",
        "    return sum(row[factor] * weight for factor, weight in weights.items())\n",
        "\n",
        "df['total_score'] = df.apply(weighted_score, axis=1)\n",
        "\n",
        "# ---------- Output ----------\n",
        "st.header(\"📊 Offer Scores\")\n",
        "st.dataframe(df[['offer_id', 'total_score']])\n",
        "\n",
        "best_offer = df.loc[df['total_score'].idxmax()]['offer_id']\n",
        "st.success(f\"✅ Based on your preferences, **{best_offer}** is the better offer.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vGWhOl4pGPOY",
        "outputId": "c839b35f-437d-48ab-a0d1-df05ce76dc0b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: streamlit in /usr/local/lib/python3.11/dist-packages (1.44.1)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.1.8)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (24.2)\n",
            "Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.1.0)\n",
            "Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.4)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (9.1.2)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.13.1)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.9.1)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.34.1)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.1.31)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.24.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-04-15 20:18:14.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.217 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.223 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.243 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.247 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.247 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.249 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.301 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:14.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: streamlit in /usr/local/lib/python3.11/dist-packages (1.44.1)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.1.8)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (24.2)\n",
            "Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.1.0)\n",
            "Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.4)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (9.1.2)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.13.1)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.9.1)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.34.1)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.1.31)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.24.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-04-15 20:18:17.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.142 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.143 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.143 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.145 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.147 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.149 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.150 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.159 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.162 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.165 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.166 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.170 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.170 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.172 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.177 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.179 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.184 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.223 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-15 20:18:17.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "DeltaGenerator()"
            ]
          },
          "metadata": {},
          "execution_count": 9
        }
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPLfk0ekah1YHMmwj8NVEkl",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}